
/*
generateMapData({
    deathplaneY: 999,
    sections: [
        {

        },{
            holdTime: 
            spawn: 
            radius: 
            trigger: 
            tp: {
                start: 
                dest: 
            },
            walls: [
                {
                    location: 
                },{
                    location: 
                }
            ]
        }
    ]
})
*/
